---
title: 'Assignment: An anlysis with NOAA Storm Database on severe weather events'
author: "Nanyuchentw"
date: "2023-10-07"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Set the environement
```{r, warning=FALSE, message=FALSE, results='hide'}
local <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_ALL", "English")
library(tidyverse)

```

## Read in data
```{r}
df <- read.csv("repdata_data_StormData.csv.bz2")
str(df)
health_cost <- df %>% group_by(EVTYPE) %>% summarise(inj= sum(INJURIES), death=sum(FATALITIES))
max_inj <- health_cost[which(health_cost$inj== max(health_cost$inj)),1:2]
max_death <- health_cost[which(health_cost$death== max(health_cost$death)),c(1,3)]

max_inj
max_death
```
With respect to population health, TORNADO is most harmful and had caused `r max_inj[1, 2]` injuries and `r max_death[1,2]` deaths.

```{r}

```



## Set the environment back
```{r}
Sys.setlocale(locale = local)
```